### ISSUE TITLE
Not really an issue - Graham and Beer Engine.

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#17]
I've been reading more at JBK Forums.
It seems Graham intended, other things to revive Beer Engine in Linux.

More  interesting reading, see Graham's post, about half way down page:

https://www.jimsbeerkit.co.uk/forum/viewtopic.php?f=77&t=17405&start=180

there is much here, including the hops formula question,
and dealing with a print option method.

**Comment by Bobbicat** [comment]
Graham wrote a 'Getting Started' manual page towards the bottom on this Forum page, it might need some editing:

https://www.jimsbeerkit.co.uk/forum/viewtopic.php?f=77&t=17405

Perhaps you should contact JBK and explain what you are doing, then ask if you could have a space on their Forum to handle input. A place to make announcements, receive feedback, deal with questions and help to perpetuate Beer Engine. 
In particular to attempt to at least partially fulfill Graham's stated intentions as far as practically possible:

> 1). Finish off the latest version of BeerEngine
2). Convert to WxPerl if I have the stomach for it
3). Restore it to native Linux as the base model. 
4). Make it universal and use switches to enable it include or exclude platform specific stuff for Windows and Mac, so that there is just one programme which packaged according to platform.


What do you think? Open Source also springs to mind, if that suits your plans.

**Comment by jimbob88** [comment]
As Graham says himself, moving over too WxPython (in my case due to the use of Python over Perl) would be one hell of a job. It would require the reprogramming of the whole interface - again as he said it would take a lot of time and effort ( the longest bit about making  WWW ) was the interface and it isn't in any way perfect. Also the biggest advantage of him moving to WxPerl was the cross-compatibility factor between Linux, Windows and MacOS, yet in Python Tk/Tcl is packaged with it. I feel WxPython looks nicer yet it would be more work and would take a long time to move over to that system ( I am also very familiar with Tk/Tcl as I have worked with it for 4 years ). 

The Open Source concept is already here in WWW, WWW is licensed under GPL-3 meaning users can share/modify/distribute it freely so that box is ticked.

The base model has already been built in Linux, Ubuntu being my main operating system means I can develop for it freely and easily. 

Not so sure about the "platform specific stuff", not exactly sure what Graham was referring to right there.
