### ISSUE TITLE
Volume to Boil Volume

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#28]
In the Engine room, enter a Volume, say 5L into the Volume box.
Click return and a boil volume will appear in the Boil Volume box.
The figure produced has a large number of decimal places.
Is a figure with just one place of decimals not adequate?

Are the calculations going on under the hood at a greater precision than is really necessary?
I'm not a programmer, as I have said before, but I do know that the precision of variables can be pre-defined.

Excuse me if, in my ignorance, I am speaking out of turn here and please feel free to ignore me if I am talking twaddle.

**Comment by jimbob88** [comment]
This seems rather odd, with 5L the maths seems to be done fine and I get the expected 5.5L yet if I test with 7L I encounter the previously found issue #26 appears again in the boil volume section. Rather than 7.7L I get `7.700000000000001` for the boil volume. I feel you are right with forcing a level of precision when working out Boil Volume (yet leaving it free for users to choose their own precision if they wish to type out a higher decimal number. With future calculations I'll use a 2 decimal place level of precision
