### ISSUE TITLE
www as menu item

### ISSUE THREAD

**Issue by radar-blip** [jimbob88/wheelers-wort-works#67]
Jim, not an issue but I have a question.

A couple weeks ago I cloned this program and was able to get it working on my system. I noticed the program showed up in my menu (as a menu item) which I thought was pretty cool.
Anyway, since then I did a clean install of the same OS (Linux mint 18) and I cant remember what I did to get the program to show up as a menu item in my menu. 
I did everything the same as before, ran the commands in the readme.md, rebooted and whatnot
Do you have any ideas?

Thanks, -Dave

**Comment by jimbob88** [comment]
Out of interest, which version of Linux Mint 18 were you using (as in which flavour)?
- Cinnamon
- KDE
- MATE
- XFCE
And 32-bit/64-bit?

Seems strange that it doesn't appear though,
I assume one of these uses a different menu system (and if so I'll try and program it so it can add Menu Items on the Desktop Environment). Hopefully, because I'm in Quarantine, I'll be able to fix it quickly (I'll install that Flavour in V-BOX and test it out)

Hope you're doing well,
Jim

**Comment by radar-blip** [comment]
Linux Mint 18 Cinnamon.  (64-bit)
The first time I installed it, GDebi Package Installer opened and started installing some files (I forgot about this part) but it probably has something to do with how the program got into the menu. I cant seem to make this happen again. Since this is a fresh install, maybe I'm missing some .deb files? 

I'm surviving, just being careful every time I go somewhere. Taking my vitamins (extra vitamin C).
Get well soon! and thanks for your help.
-Dave

**Comment by jimbob88** [comment]
Hi,
I've just installed Linux Mint 18 Cinnamon (64-bit) onto my Virtualbox System, and it seemed to work fine:
I uploaded a YouTube video documenting my setup [here](https://www.youtube.com/watch?v=fT1Kt6SuTMs).

It seems a bit strange that a Menu Item didn't appear for you as it seems to have worked for me,

Jim

**Comment by radar-blip** [comment]
Okay, I got it working now. I was going according to the 'Linux' section of the Readme. I remember now (after watching your video) that it was the community-edition I had installed before. So I clicked on releases, clicked on the first deb link, and it self-installed just like before.

Thanks again for your help!
-Dave

**Comment by radar-blip** [comment]
By the way, glancing at some of your code.. 
Line 3 of beer-engine.py, is that auto-updating  ??

Anyway, cheers!

**Comment by jimbob88** [comment]
Yeah on the windows build of Wheelers-wort-works it automatically updates; however, sadly due to the installation of WWW on Ubuntu being to a ROOT directory, one would need SUDO permissions to update the program so auto-updating is cut out of the DEB file and it has to be done manually by the update commands

**Comment by radar-blip** [comment]
I was just trying to point out a typo in the code (line 3 of beer-engine2.py) says autupdating. Not a big deal of course.
Thanks for explaining updating procedure though.

**Comment by jimbob88** [comment]
Oh yeah, sorry I didn't notice that!

Thanks very much, I've updated it to be fixed now
